# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Guru' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod ‘Parse’
  pod ‘OneSignal’

  # Pods for Guru

  target 'GuruTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GuruUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
