# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/twilio/cocoapod-specs'

target 'Guru' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod ‘Parse’
  pod 'OneSignal’, '~> 2.3.5’
  pod 'TwilioVideo', '1.0.0-beta12’
  pod 'ParseLiveQuery'
  pod 'PopupController'
  pod 'Cosmos', '~> 8.0'
  pod 'M13Checkbox'


  # Pods for Guru

  target 'GuruTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GuruUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
